### PR TITLE
LPS-72638

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/205. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
